# syntax=docker/dockerfile:1
FROM node:16

WORKDIR /code
RUN wget https://github.com/mytlogos/enterprise-lister/releases/latest/download/dist-src.zip
RUN unzip dist-src.zip
RUN npm install -g npm
RUN npm install --production
# for some reason the package ws is not installed properly
RUN npm install ws --production
COPY *.env ./
