# syntax=docker/dockerfile:1
FROM node:16.3

WORKDIR /code
RUN git clone https://github.com/mytlogos/enterprise-lister .
# by default only work on "next" branch
RUN git checkout next
# INFO: force all container to have german timezone
# reason: for (wrong) reasons the dates in the database are interpreted
# and used as local datetimes
RUN npm -g install npm
RUN npm -g install @vue/cli typescript
RUN npm install
RUN npm run build -ws
COPY *.env ./