
name: Node.js CI Lint

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'packages/**'
      - package-lock.json
      - .prettierrc.js
      - .eslintrc.js
  push:
    branches:
      - master
      - next
    paths:
      - 'packages/**'
      - package-lock.json
      - .prettierrc.js
      - .eslintrc.js

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint -ws
